### ISSUE TITLE
Go B2BUA - Radius Support

### ISSUE THREAD

**Issue by ergyspapa** [sippy/go-b2bua#16]
Dear team,
Taking a look at the perfect software you are using, I am interested to know if there will be any progress regarding development of GO B2BUA in Radius. 
Also, I can sponsor such development if it will be required!

Hope to get a response.

Thank you,

**Comment by bambyster** [comment]
Hi ergyspapa,

The b2bua_radius app is now at the feature parity with the python version. Please check it.

Thank you.

**Comment by ergyspapa** [comment]
Dear team,
I would like to congratulate for all the job that have been done and I was testing in everything the whole project.
I see there is a bug in Content Length when it is used with Radius specially when you set the a codec list id, using -F and the numbers for each codec that is being used.
This will create to sent an invite without a contact-length and with a missing body.

The second bug I found, have been while using Outbound Proxy Kamailio as it will sent ACK, Re-Invite request same at same Kamailio IP (KAMAILIO_IP : 5060)

It would be great specially if you can solve the first bug of codec, as Kamailio can be a thing can be solve in simple way.

Regards,
